name: manual-build.yml
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build/libs/
  
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    needs: build
    
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: Build
          path: build
      - run: zip -r build.zip build/
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build.zip"